package pl.saramak.dagger2;

import pl.saramak.dagger2.Application;
import pl.saramak.dagger2.twitter.DaggerTwitterComponent;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mario' at '8/22/15 8:48 AM' with Gradle 2.5
 *
 * @author mario, @date 8/22/15 8:48 AM
 */
public class Main {
    public static void main(String[] args) {
        Application application = new Application();
        DaggerTwitterComponent.create().inject(application);
        application.start();
    }
}
