import org.junit.Test;
import pl.saramak.dagger2.Main;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mario' at '8/22/15 8:48 AM' with Gradle 2.5
 *
 * @author mario, @date 8/22/15 8:48 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Main classUnderTest = new Main();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
